version: '3.8'

services:
  db:
    image: postgres:15  # 최신 안정 버전인 15 버전을 사용
    container_name: roomie-postgres
    restart: always
    ports:
      - "5432:5432"     # Postgres 기본 포트
    environment:
      POSTGRES_USER: roomie_user      # 아이디
      POSTGRES_PASSWORD: roomie_pass  # 비밀번호
      POSTGRES_DB: roomie_db          # DB 이름
    volumes:
      - ./pg_data:/var/lib/postgresql/data # 데이터 저장 폴더 이름도 변경